### ISSUE TITLE
Rename "ngw_id" output to "ids"

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/terraform-aws-nat-gateway#6]
There are a number of reasons for this change:

1. As a design point, we shouldn't prefix attributes of the module. e.g. this is the nat gateway module, the value should be the id
2. The output value is actually an array of ids and the name should reflect that
3. We want to be able to use this module interchangably with the internet gateways module so we want a name that generically represents the ouptut

**Comment by indirakalagara** [comment]
Have added ids as output.  Will cleanup once the entire architecture is tested with BOM.
